apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    nginx.ingress.kubernetes.io/client-max-body-size: 256m
  name: clientmanagement-ingress
  namespace: {{ .Values.clientmanagement.meta.namespace }}
spec:
  rules:
  - host: backend.sagespidy.com
    http:
      paths:
      - path: /client/**
        pathType: Prefix
        backend:
          service:
            name: clientmanagement
            port:
              number: 82
