apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: profilemanagement-ingress
  namespace: {{ .Values.profilemanagement.meta.namespace }}
spec:
  rules:
  - host: backend.sagespidy.com
    http:
      paths:
      - path: /profile/**
        pathType: Prefix
        backend:
          service:
            name: profilemanagement
            port:
              number: 82
